#TODO APM Server needs to be accessible from outside, so this also needs a NodePort element
{{- if .Values.apmServer.enabled }}
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
spec:
  version: 8.8.1
  count: 1
  elasticsearchRef:
    name: {{ .Values.global.elasticsearchName | quote }}
  # this allows ECK to configure automatically the Kibana endpoint as described in https://www.elastic.co/guide/en/apm/server/current/setup-kibana-endpoint.html
  kibanaRef:
    name: {{ .Values.global.kibanaName | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: apm
spec:
  selector:
    agent.k8s.elastic.co/name: {{ .Values.elasticAgent.name }}
  ports:
    - protocol: TCP
      port: 8200
{{- end }}