apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
spec:
  version: 8.8.1
  count: 1
  elasticsearchRef:
    name: {{ .Values.global.elasticsearchName }}