{{- if .Values.kibana.enabled }}

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.global.kibanaName }}
  namespace: {{ .Values.global.namespace }}
spec:
  version: 8.8.1
  count: 1
  elasticsearchRef:
    name: elastic
  config:
    enterpriseSearch.host: 'http://localhost:3002'
    xpack.fleet.agents.elasticsearch.hosts: [ "https://{{ .Values.global.elasticsearchName }}-es-http.default.svc:9200" ]
    xpack.fleet.agents.fleet_server.hosts: [ "https://{{ .Values.fleetServer.name }}-agent-http.default.svc:8220" ]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: apm
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: fleet_server-1
            id: fleet_server-1
            package:
              name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
          - package:
              name: apm
            name: apm-1
            inputs:
              - type: apm
                enabled: true
                vars:
                  - name: host
                    value: 0.0.0.0:8200
{{- end }}